# 1. Carregamento do dataset + Tratamento inicial

1.1 Importando as Blibliotecas **pandas, numpy e matplotlib.pylot**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

1.2 Criando **FUNÇÃO** para carregar um arquivo **csv** e também para salvar um arquivo **cvs** tratado

In [2]:
def carregar_banco_csv(caminho):
    return pd.read_csv(caminho)
    pass

def salvar_banco_csv(df, caminho):
    df.to_csv(caminho, index=False)

1.3 Puxando a **FUNÇÃO** através da **VARIÁVEL**, e retornando o **BANCO DE DADOS**

In [3]:
df_carregado = carregar_banco_csv(
    r"C:\Users\User\Desktop\BECKUP - PALMEIRAS\CAIXAVERSO - ADA\AULAS PRESENCIAIS\4 - TECNICAS DE PROGRAMAÇÃO I (PY) - DE 12-05-2026 A 26-05-2026\PROJETO\data_science_salaries.csv"
)
df_carregado.head()

,job_title,experience_level,employment_type,work_models,work_year,employee_residence,salary,salary_currency,salary_in_usd,company_location,company_size
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium

1.4 **Efetuando a Renomeação das Colunas e limpesas e formatações necessárias**

In [4]:
#  Renomear colunas para o padrão do sistema
df_tratado = df_carregado.rename(columns={
    "job_title": "cargo",
    "experience_level": "nivel_experiencia",
    "employment_type": "tipo_contrato",
    "work_models": "modalidade",
    "salary_in_usd": "salario_usd",
    "employee_residence": "pais_residencia",
    "salary": "salario_moeda_corrente",
    "salary_currency": "moeda_corrente",
    "company_location": "pais_empresa",
    "company_size": "porte_empresa",
    "work_year": "ano"
})
df_tratado.head()

,cargo,nivel_experiencia,tipo_contrato,modalidade,ano,pais_residencia,salario_moeda_corrente,moeda_corrente,salario_usd,pais_empresa,porte_empresa
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium

In [5]:
#  Limpeza básica
df_tratado["cargo"] = df_tratado["cargo"].astype(str).str.strip()
df_tratado["modalidade"] = df_tratado["modalidade"].astype(str).str.strip()
df_tratado["nivel_experiencia"] = df_tratado["nivel_experiencia"].astype(str).str.strip()
df_tratado.head()

,cargo,nivel_experiencia,tipo_contrato,modalidade,ano,pais_residencia,salario_moeda_corrente,moeda_corrente,salario_usd,pais_empresa,porte_empresa
0,Data Engineer,Mid-level,Full-time,Remote,2024,United States,148100,USD,148100,United States,Medium
1,Data Engineer,Mid-level,Full-time,Remote,2024,United States,98700,USD,98700,United States,Medium
2,Data Scientist,Senior-level,Full-time,Remote,2024,United States,140032,USD,140032,United States,Medium
3,Data Scientist,Senior-level,Full-time,Remote,2024,United States,100022,USD,100022,United States,Medium
4,BI Developer,Mid-level,Full-time,On-site,2024,United States,120000,USD,120000,United States,Medium

In [14]:
# Salvar com nome atualizado na mesma pasta
salvar_banco_csv(df_tratado, "salario_ciencia_dados.csv")